### ISSUE TITLE
error while packing images over 1024 file in windows 

### ISSUE THREAD

**Issue by chslink** [wo1fsea/PyTexturePacker#5]
```python
Traceback (most recent call last):
  File "E:/Code/PythonCode/UnpackGui/main.py", line 46, in <module>
  File "E:/Code/PythonCode/UnpackGui/main.py", line 41, in repackpng
  File "C:\Python27\lib\site-packages\PyTexturePacker\MaxRectsBinPacker\MaxRectsBinPacker.py", line 96, in pack
  File "C:\Python27\lib\site-packages\PyTexturePacker\Utils.py", line 47, in load_images_from_dir
  File "C:\Python27\lib\site-packages\PyTexturePacker\Utils.py", line 25, in load_images_from_paths
  File "C:\Python27\lib\site-packages\PyTexturePacker\ImageRect.py", line 33, in __init__
  File "C:\Python27\lib\site-packages\PyTexturePacker\ImageRect.py", line 52, in load_image
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 2312, in open
IOError: [Errno 24] Too many open files: 'newgui/distract.png'

```

**Comment by wo1fsea** [comment]
The bug is fixed, but I forgot to subimit the new release to pypi. Now the release version on pypi is updated. 
Use

>pip install --upgrade PyTexturePacker

to updrade the package.

BTW, thanks 4 your star.
